"""Add StudyMonth and WeeklyCheckIn

Revision ID: 13a08eee2f19
Revises: 1f3483e81853
Create Date: 2026-01-16 18:24:12.185860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a08eee2f19'
down_revision: Union[str, Sequence[str], None] = '1f3483e81853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_study_months_id'), 'study_months', ['id'], unique=False)
    op.create_table('weekly_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('q1', sa.Boolean(), nullable=True),
    sa.Column('q2', sa.Boolean(), nullable=True),
    sa.Column('q3', sa.Boolean(), nullable=True),
    sa.Column('q4', sa.Boolean(), nullable=True),
    sa.Column('q5', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_checkins_date'), 'weekly_checkins', ['date'], unique=False)
    op.create_index(op.f('ix_weekly_checkins_id'), 'weekly_checkins', ['id'], unique=False)
    
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cards_month_id_study_months', 'study_months', ['month_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cards_month_id_study_months', type_='foreignkey')
        batch_op.drop_column('month_id')
        
    op.drop_index(op.f('ix_weekly_checkins_id'), table_name='weekly_checkins')
    op.drop_index(op.f('ix_weekly_checkins_date'), table_name='weekly_checkins')
    op.drop_table('weekly_checkins')
    op.drop_index(op.f('ix_study_months_id'), table_name='study_months')
    op.drop_table('study_months')
    # ### end Alembic commands ###